config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users ,:controllers => { :registrations => "registrations" }
  
  resources :groups do
    member do
      get 'remainders'
    end
    resources :remainders
    resources :members
  end
  
  namespace :admin do
    get 'pages' => 'pages#index'
    resources :users, only: [:index, :show, :destroy] do
      resources :groups do
        member do
          get 'remainders'
        end
        resources :remainders
        resources :members
      end
    end  
  end

  root to: 'pages#index'

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :members
  has_many :remainders


  accepts_nested_attributes_for :members, :allow_destroy => true

end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :group
end

app/models/remainder.rb
class Remainder < ActiveRecord::Base
  belongs_to :group
  validates :name, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups, dependent: :destroy
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  layout 'admin'
  def index
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  # GET /admin/users.json
  def index
    @users = User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @user = User.find(params[:id])
    end
end

app/controllers/admin_controller.rb
class AdminController < ActionController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy, :remainders]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = current_user.groups.build
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups.build(group_params)
    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_path, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remainders
    @remainders = @group.remainders
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through. members_attributes
    def group_params
      params.require(:group).permit(:name, :contact, :status, :user_id, members_attributes: [:id, :name, :contact, :group_id, :_destroy])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController <  Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :mobile_no, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :mobile_no)
  end
end

app/controllers/remainders_controller.rb
class RemaindersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_remainder, only: [:show, :edit, :update, :destroy]
  before_action :set_group, only: [:create, :update, :destroy, :new]

  # GET /remainders
  # GET /remainders.json
  def index
    @remainders = Remainder.all
  end

  # GET /remainders/1
  # GET /remainders/1.json
  def show
  end

  # GET /remainders/new
  def new
    @remainder = @group.remainders.new
  end

  # GET /remainders/1/edit
  def edit
  end

  # POST /remainders
  # POST /remainders.json
  def create
    binding.pry
    @remainder = @group.remainders.new(remainder_params)
    respond_to do |format|
      if @remainder.save
        format.html { redirect_to group_remainders_path(@group), notice: 'Remainder was successfully created.' }
        format.json { render :show, status: :created, location: @remainder }
      else
        format.html { render :new }
        format.json { render json: @remainder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /remainders/1
  # PATCH/PUT /remainders/1.json
  def update
    respond_to do |format|
      if @remainder.update(remainder_params)
        format.html { redirect_to group_remainders_path(@group), notice: 'Remainder was successfully updated.' }
        format.json { render :show, status: :ok, location: @remainder }
      else
        format.html { render :edit }
        format.json { render json: @remainder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remainders/1
  # DELETE /remainders/1.json
  def destroy
    @remainder.destroy
    respond_to do |format|
      format.html { redirect_to group_remainders_path(@group), notice: 'Remainder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remainder
      @remainder = Remainder.find(params[:id])
    end

    def set_group
      @group = Group.find(params[:group_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def remainder_params
      params.require(:remainder).permit(:name, :start_date, :end_date, :remainder_time, :schedule_interval, :message, :group_id, :status)
    end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def edit_icon
   raw("<span class ='badge icon-pad info-bg'><i class='fa fa-pencil fa-1x'></i>&nbsp; Edit</span>").html_safe 
  end
  def delete_icon
  	raw("<span class ='badge icon-pad danger-bg'><i class='fa fa-trash'></i> &nbsp; Delete </span>").html_safe
  end
  def show_icon
  	raw("<span class ='badge icon-pad'><i class='fa fa-eye'></i> &nbsp; View </span>").html_safe
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/remainders_helper.rb
module RemaindersHelper
end

app/views/admin/users/index.html.erb
<div>  
  <h1 class="title">Listing Users</h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Email</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Mobile no</th>
        <th>Address</th>
        <th colspan="2">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.mobile_no %></td>
          <td><%= user.address %></td>
          <td><%= link_to show_icon, admin_user_path(user) %></td>
          <td><%= link_to delete_icon, admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Mobile no:</strong>
  <%= @user.mobile_no %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<%= link_to 'Back', admin_users_path %>

app/views/groups/_form.html.erb
<%= nested_form_for(@group, html: { class: "form-horizontal"} )do |f| %>
  <div class="form-group"> 
    <div class="col-sm-12">
      <%= f.text_field :name, :class => "form-control",  placeholder: "Enter Group name"%>
    </div>
  </div>
  <%= f.fields_for :members do |ff| %>
    <div class="form-group"> 
      <div class="col-sm-5">
        <%= ff.text_field :name, :class => "form-control",  placeholder: "Enter Member name"%>
      </div>
      <div class="col-sm-5">
       <%= ff.text_field :contact, :class => "form-control",  placeholder: "Enter Contact number"%>
      </div>
      <div class="col-sm-2">
         <%= ff.link_to_remove "Remove", class: "btn btn-danger form-control"%>
      </div>
    </div>
  <% end %>
     
  <%= f.link_to_add "Add Member", :members, class: "btn btn-warning pull-right"%>
  <%= f.submit class: "btn btn-success"%> 
<% end %> 

app/views/groups/edit.html.erb
<h1 class ="title">Editing Group</h1>
<div class="wrapper">
  <%= render 'form' %>
</div>

app/views/groups/index.html.erb
<div class="">
  <h1 class = "title">Listing Groups</h1>
  <table id="groups" class="table table-bordered wrapper">
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
        <th>Action</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td><%= link_to group.name.titleize, remainders_group_path(group) %></td>
          <td><%= group.status %></td>
          <td><%= link_to edit_icon, edit_group_path(group) %></td>
          <td><%= link_to delete_icon, group, method: :delete, data: { confirm: 'Are you sure?'} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
  <%= link_to "Create New Group", new_group_path, class: "btn btn-success" %>
  </div>
</div>

app/views/groups/new.html.erb
<h1 class ="title">Create New Group</h1>
<div class="wrapper">
  <%= render 'form' %>
</div>

app/views/groups/remainders.html.erb
<div class =""> 
  <h1 class = "title">Listing Remainders</h1>
  <table class= "table table-bordered table-responsive wrapper">
    <thead>
      <tr>
        <th>Name</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Remainder time</th>
        <th>Schedule interval</th>
        <th>Message</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @remainders.each do |remainder| %>
        <tr>
          <td><%= remainder.name %></td>
          <td><%= remainder.start_date %></td>
          <td><%= remainder.end_date %></td>
          <td><%= remainder.remainder_time %></td>
          <td><%= remainder.schedule_interval %></td>
          <td><%= remainder.message %></td>
          <td><%= link_to show_icon, group_remainder_path(@group, remainder)  %></td>
          <td><%= link_to edit_icon, edit_group_remainder_path(@group, remainder) %></td>
          <td><%= link_to delete_icon, group_remainder_path(@group, remainder), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
    <%= link_to 'New Remainder', new_group_remainder_path(@group), class: "btn btn-success" %>
  </div>
</div>

app/views/groups/show.html.erb
<div class ="container">
	<p>
	  <strong>Name:</strong>
	  <%= @group.name %>
	</p>
	
	<p>
	  <strong>Status:</strong>
	  <%= @group.status %>
	</p>
	
	<p>
	  <strong>User:</strong>
	  <%= @group.user %>
	</p>
	
<div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default menu">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% unless user_signed_in?%>
          <li> 
            <%= link_to 'Login', user_session_path %>
          </li>
        <% else %>
          <li> <%= link_to 'Groups', groups_path %> </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li> 
                <%= link_to('Edit Profile', edit_user_registration_path) %>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>        
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemainderManagement</title>
    <%= stylesheet_link_tag  'admin', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
     <div>
      <% if alert %>
        <div class= "alert alert-danger text-center">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemainderManagement</title>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar'%>
    <div class ="container">
      <% if alert %>
        <div class= "alert alert-danger text-center">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class= "container">
  <h1> Welcome to Remainder management bulk Messaging </h1>
</div>

app/views/remainders/_form.html.erb
<%= form_for(@remainder, url: group_remainders_path, html: { class: "form-horizontal"},  method: :post ) do |f| %>
  <div class="form-group"> 
    <div class="col-sm-12">
      <%= f.text_field :name, :class => "form-control",  placeholder: "Enter Remainder name"%>
    </div>
  </div>

  <div class="form-group"> 
    <div class="col-sm-6">
      <%= f.text_field :start_date, :class => "form-control datepicker",  placeholder: "Select Start Date"%>
    </div>
  </div>

  <div class="form-group"> 
    <div class="col-sm-6">
      <%= f.text_field :remainder_time, :class => "form-control datetimepicker",  placeholder: "Select Remainder Time"%>
    </div>
    <div class="col-sm-6">
     <%= f.select :schedule_interval,["30","40","50","60","70","80","90","100","110","120","130","140","150"],{prompt:"Select schedule interval in days"},style: "width:200px",class: "form-control"%>
    </div>
  </div>

  <div class="form-group"> 
    <div class="col-sm-12">
      <%= f.text_area :message, :class => "form-control",  placeholder: "Enter Message"%>
    </div>
  </div>
  
  <div class="form-group"> 
    <div class="text-center">
      <%= f.submit class: "btn btn-success"%>
    </div>
  </div>
<% end %>

app/views/remainders/edit.html.erb
<h1 class ="title">Editing Remainder</h1>
<div class="wrapper">
  <%= render 'form' %>
</div>

app/views/remainders/index.html.erb
<div class="container">
<h1 class = "title">Listing Remainders</h1>

<table class= "table table-bordered wrapper">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Remainder time</th>
      <th>Schedule interval</th>
      <th>Message</th>
      <th>Group</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @remainders.each do |remainder| %>
      <tr>
        <td><%= remainder.name %></td>
        <td><%= remainder.start_date %></td>
        <td><%= remainder.end_date %></td>
        <td><%= remainder.remainder_time %></td>
        <td><%= remainder.schedule_interval %></td>
        <td><%= remainder.message %></td>
        <td><%= remainder.group %></td>
        <td><%= remainder.status %></td>
        <td><%= link_to 'Show', remainder %></td>
        <td><%= link_to 'Edit', edit_remainder_path(remainder) %></td>
        <td><%= link_to 'Destroy', remainder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Remainder', new_remainder_path, class: "btn btn-success" %>
</div>

app/views/remainders/new.html.erb
<h1 class = "title"> Create New Remainder</h1>
<div class="wrapper">
  <%= render 'form' %>
</div>

app/views/remainders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @remainder.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @remainder.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @remainder.end_date %>
</p>

<p>
  <strong>Remainder time:</strong>
  <%= @remainder.remainder_time %>
</p>

<p>
  <strong>Schedule interval:</strong>
  <%= @remainder.schedule_interval %>
</p>

<p>
  <strong>Message:</strong>
  <%= @remainder.message %>
</p>

<p>
  <strong>Group:</strong>
  <%= @remainder.group.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @remainder.status %>
</p>

<%= link_to 'Edit', edit_group_remainder_path(@remainder.group, @remainder) %> |
<%= link_to 'Back', remainders_group_path(@remainder.group) %>